version: '2'

services:

  ###############################################
  #                  Webserver                  #
  ###############################################

  lastfm-php:
    build:
      context: .
      dockerfile: docker_php.Dockerfile
      args:
        - ENV=dev
    container_name: "lastfm_php_dev"
    ports:
      - "9000"
    env_file:
      - .env
    volumes:
      - ./backend:/code/site

  ###############################################
  #                    Nginx                    #
  ###############################################

  lastfm-nginx:
    build:
      context: .
      dockerfile: docker_nginx.Dockerfile
      args:
        - ENV=dev
    container_name: "lastfm_nginx_dev"
    ports:
      - "8092:80"
    volumes:
      - ./_docker/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - lastfm-php
    links:
      - lastfm-php
